### ISSUE TITLE
请问一下这个是什么问题

### ISSUE THREAD

**Issue by lovezm** [wforguo/wedding-app#12]
D:\xiaochengxu\wedding-app-master> yarn dev:weapp
yarn run v1.22.10
$ npm run build:weapp -- --watch

> weapp@1.0.0 build:weapp
> taro build --type weapp "--watch"

👽 Taro v2.1.3

开始编译项目 wedding
生成  工具配置  dist/project.config.json
D:\xiaochengxu\wedding-app-master\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
            ^

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (D:\xiaochengxu\wedding-app-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\xiaochengxu\wedding-app-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\xiaochengxu\wedding-app-master\node_modules\@tarojs\mini-runner\dist\webpack\chain.js:8:14)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (D:\xiaochengxu\wedding-app-master\node_modules\@tarojs\mini-runner\dist\webpack\build.conf.js:4:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lovezm** [comment]
解决了 版本过高 用了node v16 换成v14就好了

**Comment by web-farmer** [comment]
> 解决了 版本过高 用了node v16 换成v14就好了

是的，对node版本有要求，主要是taro2 对应node版本有要求，

感谢留下您的star
